### ISSUE TITLE
"C:\WINDOWS\sysnative\cmd.exe" is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by Alebat** [koltyakov/cpass#6]
Hi, while I was playing with [sp-pnp-node](https://github.com/koltyakov/sp-pnp-node), I often found the following message in my terminal (italian):

> "C:\WINDOWS\sysnative\cmd.exe" non ´┐¢ riconosciuto come comando interno o esterno, un programma eseguibile o un file batch.

I think I solved the problem by editing the following file: [https://github.com/koltyakov/cpass/blob/master/src/utils/machineId.ts](https://github.com/koltyakov/cpass/blob/master/src/utils/machineId.ts)

Instead of using `sysnative` virtual folder to locate cmd.exe for ia32 I use System32, letting the OS do the redirects.

I don't know btw why the `ia32` path is used on my Windows 10 x64 system instead of the 'x64' one (no 32-bit processes in Task Manager).

**Comment by koltyakov** [comment]
Thanks, @Alebat,

Any ideas on how to reproduce? I've never seen the error you mentioned before. And the agents for testing in windows are Win 10 x64, Win Server x64.

Anyways, thanks, I'll take a look before merging the change.

**Comment by Alebat** [comment]
These are the versions by vscode:
```
Version: 1.33.1 (user setup)
Commit: 51b0b28134d51361cf996d2f0a1c698247aeabd8
Date: 2019-04-11T08:27:14.102Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763
```

Download, extract and add to PATH https://nodejs.org/dist/latest-v10.x/node-v10.15.3-win-x64.7z

Run in an empty folder:
```
npm init
npm i sp-pnp-node @pnp/pnpjs --save
```

Integrate package.json with:
```
{
  "scripts": {
    "start": "node ."
  }
}
```
Create `index.js` with the following code (as a translation of the **Minimal setup** here --> https://www.npmjs.com/package/sp-pnp-node)

```js
var sp_1 = require('@pnp/sp');
var sp_pnp_node_1 = require('sp-pnp-node');
new sp_pnp_node_1.PnpNode().init().then(function (settings) {
    var web = new sp_1.Web(settings.siteUrl);
    /// ... // <<< Here goes PnP JS Core code
}).catch(console.log);
```

Run:
```
npm start
```
The output should contain the localized title of this issue.

**Comment by jesus614** [comment]
> Hi, while I was playing with [sp-pnp-node](https://github.com/koltyakov/sp-pnp-node), I often found the following message in my terminal (italian):
> 
> > "C:\WINDOWS\sysnative\cmd.exe" non ´┐¢ riconosciuto come comando interno o esterno, un programma eseguibile o un file batch.
> 
> I think I solved the problem by editing the following file: https://github.com/koltyakov/cpass/blob/master/src/utils/machineId.ts
> 
> Instead of using `sysnative` virtual folder to locate cmd.exe for ia32 I use System32, letting the OS do the redirects.
> 
> I don't know btw why the `ia32` path is used on my Windows 10 x64 system instead of the 'x64' one (no 32-bit processes in Task Manager).

I understand it is necessary to modify the file, in which path in windows is that file to modify it or do I have to run that file as a shell?
