### ISSUE TITLE
simple-encryptor version

### ISSUE THREAD

**Issue by Alebat** [koltyakov/cpass#8]
Please update simple-encryptor to version 3.0.0 to make cpass work wth electron.

**Comment by koltyakov** [comment]
Updated. Published cpass@2.1.0-beta1. Could you please test if it works for you. Later on, I got to test some libraries which use cpass as a dependency before publishing with the latest tag.

**Comment by Alebat** [comment]
I am using it through https://www.npmjs.com/package/sp-pnp-node. If I manually apply this edit in the module folder in 'node_modules', the problem is solved and the authentication works.

**Comment by koltyakov** [comment]
Thanks! I'm going publishing the new versions with the latest tag over the weekend after some additional tests I'm thinking of.

**Comment by koltyakov** [comment]
Internal tests went well. Published the update with the latest tag. Thank you @Alebat for the contribution.
